IF EXISTS (SELECT * FROM sys.tables  WHERE OBJECT_ID=  OBJECT_ID('dbo.tbl_C1_Interface_CustomerFlow_exportfile')
		  ) BEGIN
			IF NOT EXISTS (select 1 from sys.columns  where OBJECT_ID = OBJECT_ID('dbo.tbl_C1_Interface_CustomerFlow_exportfile')and name = 'delivery_date'
						  ) ALTER TABLE [dbo].[tbl_C1_Interface_CustomerFlow_exportfile] ADD  delivery_date	DATETIME2(6) NULL ;
			END		  
ELSE    
			CREATE TABLE [dbo].[tbl_C1_Interface_CustomerFlow_exportfile] (
						 delivery_date					  DATETIME2(6) NULL,
						 rnk                              BIGINT , 
						 trck_ID                          INT , 
						 trck_touchpoint                  NVARCHAR(255) , 
						 trck_uniqueID                    NVARCHAR(255) , 
						 trck_market                      NVARCHAR(3) , 
						 trck_division                    NVARCHAR(255) , 
						 trck_brand                       NVARCHAR(128) , 
						 trck_segment                     NVARCHAR(255) , 
						 trck_email_address               NVARCHAR(128) , 
						 trck_registration_date           DATETIME , 
						 trck_creation_date               DATETIME , 
						 trck_subscribtion_date           DATETIME , 
						 trck_doi                         INT , 
						 trck_is_unsubscribed             INT , 
						 trck_unsubscribe_date            DATETIME , 
						 trck_is_contactable              INT , 
						 trck_last_edited_date            DATETIME , 
						 trck_company_name                NVARCHAR(255) , 
						 trck_title                       NVARCHAR(255) , 
						 trck_first_name                  NVARCHAR(255) , 
						 trck_last_name                   NVARCHAR(255) , 
						 trck_additional_name_information NVARCHAR(255) , 
						 trck_street                      NVARCHAR(255) , 
						 trck_house_number                NVARCHAR(255) , 
						 trck_additional_address          NVARCHAR(255) , 
						 trck_zip_code                    NVARCHAR(255) , 
						 trck_city                        NVARCHAR(255) , 
						 trck_state                       NVARCHAR(255) , 
						 trck_country                     NVARCHAR(3) , 
						 trck_gender                      NVARCHAR(255) , 
						 trck_birthday                    DATE , 
						 trck_consent_text                NVARCHAR(MAX) , 
						 trck_language                    NVARCHAR(3) , 
						 trck_mobile_number               NVARCHAR(255) , 
						 trck_landline_number             NVARCHAR(255) , 
						 trck_last_contact_date           DATETIME , 
						 trck_last_open_date              DATETIME , 
						 trck_last_click_date             DATETIME , 
						 trck_is_fake                     INT , 
						 trck_DMR                         DATETIME , 
						 trck_DCR                         DATETIME , 
						 trck_Source                      NVARCHAR(255) , 
						 trck_is_blocked                  INT , 
						 trck_blockreason                 NVARCHAR(255) , 
						 trck_change_comment              NVARCHAR(4000) , 
						 trck_custom_1                    NVARCHAR(255) , 
						 trck_custom_2                    NVARCHAR(255) , 
						 trck_custom_3                    NVARCHAR(255) , 
						 trck_custom_4                    NVARCHAR(255) , 
						 trck_custom_5                    NVARCHAR(255) , 
						 trck_custom_6                    NVARCHAR(255) , 
						 trck_custom_7                    NVARCHAR(255) , 
						 trck_custom_8                    NVARCHAR(255) , 
						 trck_custom_9                    NVARCHAR(255) , 
						 AC_AcceptancyDate                DATETIME , 
						 AC_Status                        VARCHAR(50) , 
						 AC_UnsubscribeDate               DATETIME , 
						 trck_is_consent                  INT , 
						 trck_is_participation            INT , 
						 trck_participation_text          NVARCHAR(4000) , 
						 trck_is_subscribe                INT , 
						 trck_subscribe_text              NVARCHAR(4000) , 
						 trck_is_usage                    INT , 
						 trck_usage_text                  NVARCHAR(4000) , 
						 trck_campaign                    NVARCHAR(255) , 
						 trck_referer                     NVARCHAR(255) , 
						 trck_registration_ip             NVARCHAR(255) , 
						 trck_subscribtion_ip             NVARCHAR(255) , 
						 trck_subscribtion_source         NVARCHAR(255) , 
						 trck_payload                     NVARCHAR(4000) , 
						 Jobcode14                        VARCHAR(50) , 
						 trck_source_system               VARCHAR(255)
			)
GO

IF EXISTS  (SELECT 1 FROM sys.views  WHERE OBJECT_ID=  OBJECT_ID('dbo.vw_C1_Interface_CustomerFlow_exportfile')
			)	drop view  dbo.vw_C1_Interface_CustomerFlow_exportfile;
GO
create view dbo.vw_C1_Interface_CustomerFlow_exportfile
	as select	[rnk], 
				[trck_ID], 
				[trck_touchpoint], 
				[trck_uniqueID], 
				[trck_market], 
				[trck_division], 
				[trck_brand], 
				[trck_segment], 
				[trck_email_address], 
				[trck_registration_date], 
				[trck_creation_date], 
				[trck_subscribtion_date], 
				[trck_doi], 
				[trck_is_unsubscribed], 
				[trck_unsubscribe_date], 
				[trck_is_contactable], 
				[trck_last_edited_date], 
				[trck_company_name], 
				[trck_title], 
				[trck_first_name], 
				[trck_last_name], 
				[trck_additional_name_information], 
				[trck_street], 
				[trck_house_number], 
				[trck_additional_address], 
				[trck_zip_code], 
				[trck_city], 
				[trck_state], 
				[trck_country], 
				[trck_gender], 
				[trck_birthday], 
				[trck_consent_text], 
				[trck_language], 
				[trck_mobile_number], 
				[trck_landline_number], 
				[trck_last_contact_date], 
				[trck_last_open_date], 
				[trck_last_click_date], 
				[trck_is_fake], 
				[trck_DMR], 
				[trck_DCR], 
				[trck_Source], 
				[trck_is_blocked], 
				[trck_blockreason], 
				[trck_change_comment], 
				[trck_custom_1], 
				[trck_custom_2], 
				[trck_custom_3], 
				[trck_custom_4], 
				[trck_custom_5], 
				[trck_custom_6], 
				[trck_custom_7], 
				[trck_custom_8], 
				[trck_custom_9], 
				[AC_AcceptancyDate], 
				[AC_Status], 
				[AC_UnsubscribeDate], 
				[trck_is_consent], 
				[trck_is_participation], 
				[trck_participation_text], 
				[trck_is_subscribe], 
				[trck_subscribe_text], 
				[trck_is_usage], 
				[trck_usage_text], 
				[trck_campaign], 
				[trck_referer], 
				[trck_registration_ip], 
				[trck_subscribtion_ip], 
				[trck_subscribtion_source], 
				[trck_payload], 
				[Jobcode14], 
				[trck_source_system] from  dbo.tbl_C1_Interface_CustomerFlow_exportfile where delivery_date is null;
GO


IF EXISTS( SELECT 1	FROM sys.procedures WHERE OBJECT_ID = OBJECT_ID('dbo.process_C1_Interface_FileExport')
		 ) DROP PROCEDURE dbo.process_C1_Interface_FileExport;	
GO		 
CREATE PROCEDURE process_C1_Interface_FileExport
AS	
     BEGIN
		 INSERT INTO dbo.vw_C1_Interface_CustomerFlow_exportfile
         SELECT [rnk], 
                [trck_ID], 
                [trck_touchpoint], 
                [trck_uniqueID], 
                [trck_market], 
                [trck_division], 
                [trck_brand], 
                [trck_segment], 
                [trck_email_address], 
                [trck_registration_date], 
                [trck_creation_date], 
                [trck_subscribtion_date], 
                [trck_doi], 
                [trck_is_unsubscribed], 
                [trck_unsubscribe_date], 
                [trck_is_contactable], 
                [trck_last_edited_date], 
                [trck_company_name], 
                [trck_title], 
                [trck_first_name], 
                [trck_last_name], 
                [trck_additional_name_information], 
                [trck_street], 
                [trck_house_number], 
                [trck_additional_address], 
                [trck_zip_code], 
                [trck_city], 
                [trck_state], 
                [trck_country], 
                [trck_gender], 
                [trck_birthday], 
                [trck_consent_text], 
                [trck_language], 
                [trck_mobile_number], 
                [trck_landline_number], 
                [trck_last_contact_date], 
                [trck_last_open_date], 
                [trck_last_click_date], 
                [trck_is_fake], 
                [trck_DMR], 
                [trck_DCR], 
                [trck_Source], 
                [trck_is_blocked], 
                [trck_blockreason], 
                [trck_change_comment], 
                [trck_custom_1], 
                [trck_custom_2], 
                [trck_custom_3], 
                [trck_custom_4], 
                [trck_custom_5], 
                [trck_custom_6], 
                [trck_custom_7], 
                [trck_custom_8], 
                [trck_custom_9], 
                [AC_AcceptancyDate], 
                [AC_Status], 
                [AC_UnsubscribeDate], 
                [trck_is_consent], 
                [trck_is_participation], 
                [trck_participation_text], 
                [trck_is_subscribe], 
                [trck_subscribe_text], 
                [trck_is_usage], 
                [trck_usage_text], 
                [trck_campaign], 
                [trck_referer], 
                [trck_registration_ip], 
                [trck_subscribtion_ip], 
                [trck_subscribtion_source], 
                [trck_payload], 
                [Jobcode14], 
                [trck_source_system]           
         FROM dbo.tbl_C1_Interface_CustomerFlow c1icf
         WHERE EXISTS
         (
             SELECT ist.[rnk], 
                    ist.[trck_ID], 
                    ist.[trck_touchpoint] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_uniqueID] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_market] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_division] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_brand] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_segment] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_email_address] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_registration_date], 
                    ist.[trck_creation_date], 
                    ist.[trck_subscribtion_date], 
                    ist.[trck_doi], 
                    ist.[trck_is_unsubscribed], 
                    ist.[trck_unsubscribe_date], 
                    ist.[trck_is_contactable], 
                    ist.[trck_last_edited_date], 
                    ist.[trck_company_name] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_title] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_first_name] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_last_name] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_additional_name_information] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_street] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_house_number] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_additional_address] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_zip_code] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_city] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_state] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_country] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_gender] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_birthday], 
                    ist.[trck_consent_text] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_language] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_mobile_number] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_landline_number] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_last_contact_date], 
                    ist.[trck_last_open_date], 
                    ist.[trck_last_click_date], 
                    ist.[trck_is_fake], 
                    ist.[trck_DMR], 
                    ist.[trck_DCR], 
                    ist.[trck_Source] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_is_blocked], 
                    ist.[trck_blockreason] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_change_comment] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_custom_1] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_custom_2] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_custom_3] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_custom_4] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_custom_5] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_custom_6] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_custom_7] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_custom_8] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_custom_9] COLLATE DATABASE_DEFAULT, 
                    ist.[AC_AcceptancyDate], 
                    ist.[AC_Status] COLLATE DATABASE_DEFAULT, 
                    ist.[AC_UnsubscribeDate], 
                    ist.[trck_is_consent], 
                    ist.[trck_is_participation], 
                    ist.[trck_participation_text] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_is_subscribe], 
                    ist.[trck_subscribe_text] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_is_usage], 
                    ist.[trck_usage_text] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_campaign] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_referer] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_registration_ip] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_subscribtion_ip] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_subscribtion_source] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_payload] COLLATE DATABASE_DEFAULT, 
                    ist.[Jobcode14] COLLATE DATABASE_DEFAULT, 
                    ist.[trck_source_system] COLLATE DATABASE_DEFAULT
             FROM dbo.[tbl_TrackOne_MasterData_prepare] AS ist
             WHERE ist.[trck_email_address] COLLATE DATABASE_DEFAULT = c1icf.[trck_email_address] COLLATE DATABASE_DEFAULT
                   AND ist.[trck_market] COLLATE DATABASE_DEFAULT = c1icf.[trck_market] COLLATE DATABASE_DEFAULT
                   AND ist.[trck_brand] COLLATE DATABASE_DEFAULT = c1icf.[trck_brand] COLLATE DATABASE_DEFAULT
             EXCEPT
             SELECT ita.[rnk], 
                    ita.[trck_ID], 
                    ita.[trck_touchpoint] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_uniqueID] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_market] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_division] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_brand] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_segment] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_email_address] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_registration_date], 
                    ita.[trck_creation_date], 
                    ita.[trck_subscribtion_date], 
                    ita.[trck_doi], 
                    ita.[trck_is_unsubscribed], 
                    ita.[trck_unsubscribe_date], 
                    ita.[trck_is_contactable], 
                    ita.[trck_last_edited_date], 
                    ita.[trck_company_name] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_title] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_first_name] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_last_name] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_additional_name_information] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_street] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_house_number] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_additional_address] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_zip_code] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_city] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_state] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_country] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_gender] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_birthday], 
                    ita.[trck_consent_text] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_language] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_mobile_number] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_landline_number] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_last_contact_date], 
                    ita.[trck_last_open_date], 
                    ita.[trck_last_click_date], 
                    ita.[trck_is_fake], 
                    ita.[trck_DMR], 
                    ita.[trck_DCR], 
                    ita.[trck_Source] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_is_blocked], 
                    ita.[trck_blockreason] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_change_comment] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_custom_1] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_custom_2] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_custom_3] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_custom_4] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_custom_5] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_custom_6] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_custom_7] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_custom_8] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_custom_9] COLLATE DATABASE_DEFAULT, 
                    ita.[AC_AcceptancyDate], 
                    ita.[AC_Status] COLLATE DATABASE_DEFAULT, 
                    ita.[AC_UnsubscribeDate], 
                    ita.[trck_is_consent], 
                    ita.[trck_is_participation], 
                    ita.[trck_participation_text] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_is_subscribe], 
                    ita.[trck_subscribe_text] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_is_usage], 
                    ita.[trck_usage_text] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_campaign] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_referer] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_registration_ip] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_subscribtion_ip] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_subscribtion_source] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_payload] COLLATE DATABASE_DEFAULT, 
                    ita.[Jobcode14] COLLATE DATABASE_DEFAULT, 
                    ita.[trck_source_system] COLLATE DATABASE_DEFAULT
             FROM dbo.[tbl_TrackOne_MasterData] AS ita
             WHERE ita.[trck_email_address] COLLATE DATABASE_DEFAULT = c1icf.[trck_email_address] COLLATE DATABASE_DEFAULT
                   AND ita.[trck_market] COLLATE DATABASE_DEFAULT = c1icf.[trck_market] COLLATE DATABASE_DEFAULT
                   AND ita.[trck_brand] COLLATE DATABASE_DEFAULT = c1icf.[trck_brand] COLLATE DATABASE_DEFAULT
         )
               AND COALESCE(COALESCE(CAST(rnk AS VARCHAR(23)), ''), COALESCE(CAST(trck_ID AS VARCHAR(23)), ''), trck_touchpoint, trck_uniqueID, trck_market, trck_division, trck_brand, trck_segment, trck_email_address, COALESCE(CAST(trck_registration_date AS VARCHAR(23)), ''), COALESCE(CAST(trck_creation_date AS VARCHAR(23)), ''), COALESCE(CAST(trck_subscribtion_date AS VARCHAR(23)), ''), COALESCE(CAST(trck_doi AS VARCHAR(23)), ''), COALESCE(CAST(trck_is_unsubscribed AS VARCHAR(23)), ''), COALESCE(CAST(trck_unsubscribe_date AS VARCHAR(23)), ''), COALESCE(CAST(trck_is_contactable AS VARCHAR(23)), ''), COALESCE(CAST(trck_last_edited_date AS VARCHAR(23)), ''), trck_company_name, trck_title, trck_first_name, trck_last_name, trck_additional_name_information, trck_street, trck_house_number, trck_additional_address, trck_zip_code, trck_city, trck_state, trck_country, trck_gender, COALESCE(CAST(trck_birthday AS VARCHAR(23)), ''), trck_consent_text, trck_language, trck_mobile_number, trck_landline_number, COALESCE(CAST(trck_last_contact_date AS VARCHAR(23)), ''), COALESCE(CAST(trck_last_open_date AS VARCHAR(23)), ''), COALESCE(CAST(trck_last_click_date AS VARCHAR(23)), ''), COALESCE(CAST(trck_is_fake AS VARCHAR(23)), ''), COALESCE(CAST(trck_DMR AS VARCHAR(23)), ''), COALESCE(CAST(trck_DCR AS VARCHAR(23)), ''), trck_Source, COALESCE(CAST(trck_is_blocked AS VARCHAR(23)), ''), trck_blockreason, trck_change_comment, trck_custom_1, trck_custom_2, trck_custom_3, trck_custom_4, trck_custom_5, trck_custom_6, trck_custom_7, trck_custom_8, trck_custom_9, COALESCE(CAST(AC_AcceptancyDate AS VARCHAR(23)), ''), AC_Status, COALESCE(CAST(AC_UnsubscribeDate AS VARCHAR(23)), ''), COALESCE(CAST(trck_is_consent AS VARCHAR(23)), ''), COALESCE(CAST(trck_is_participation AS VARCHAR(23)), ''), trck_participation_text, COALESCE(CAST(trck_is_subscribe AS VARCHAR(23)), ''), trck_subscribe_text, COALESCE(CAST(trck_is_usage AS VARCHAR(23)), ''), trck_usage_text, trck_campaign, trck_referer, trck_registration_ip, trck_subscribtion_ip, trck_subscribtion_source, trck_payload, Jobcode14, trck_source_system) IS NOT NULL;
     END;
GO


IF EXISTS( SELECT 1	FROM sys.procedures WHERE OBJECT_ID = OBJECT_ID('dbo.prc_C1_process_flow')
		 ) DROP PROCEDURE dbo.prc_C1_process_flow;	
GO	
CREATE PROCEDURE dbo.prc_C1_process_flow
	AS DECLARE	
		@delivery_date DATETIME2= GETDATE(); 
	BEGIN
		exec process_TrackOne_stageload					
		exec process_TrackOne_deltaCalculation
		exec process_C1_Interface_FileExport
		exec process_TrackOne_MasterDataEx	
	END;
GO	


IF EXISTS( SELECT 1	FROM sys.procedures WHERE OBJECT_ID = OBJECT_ID('dbo.prc_C1_Interface_CustomerFlow_seal_exportfile')
		 ) DROP PROCEDURE dbo.prc_C1_Interface_CustomerFlow_seal_exportfile;	
GO	
CREATE PROCEDURE dbo.prc_C1_Interface_CustomerFlow_seal_exportfile
	AS DECLARE	
		@delivery_date DATETIME2= GETDATE(); 
	BEGIN
		UPDATE	dbo.tbl_C1_Interface_CustomerFlow_exportfile
			SET delivery_date = @delivery_date WHERE delivery_date IS NULL;
	END;
GO												    
