
--
-- instead merge insert
INSERT INTO dbo.[tbl_TrackOne_MasterData]
([rnk], 
 [trck_ID], 
 [trck_touchpoint], 
 [trck_uniqueID], 
 [trck_market], 
 [trck_division], 
 [trck_brand], 
 [trck_segment], 
 [trck_email_address], 
 [trck_registration_date], 
 [trck_creation_date], 
 [trck_subscribtion_date], 
 [trck_doi], 
 [trck_is_unsubscribed], 
 [trck_unsubscribe_date], 
 [trck_is_contactable], 
 [trck_last_edited_date], 
 [trck_company_name], 
 [trck_title], 
 [trck_first_name], 
 [trck_last_name], 
 [trck_additional_name_information], 
 [trck_street], 
 [trck_house_number], 
 [trck_additional_address], 
 [trck_zip_code], 
 [trck_city], 
 [trck_state], 
 [trck_country], 
 [trck_gender], 
 [trck_birthday], 
 [trck_consent_text], 
 [trck_language], 
 [trck_mobile_number], 
 [trck_landline_number], 
 [trck_last_contact_date], 
 [trck_last_open_date], 
 [trck_last_click_date], 
 [trck_is_fake], 
 [trck_DMR], 
 [trck_DCR], 
 [trck_Source], 
 [trck_is_blocked], 
 [trck_blockreason], 
 [trck_change_comment], 
 [trck_custom_1], 
 [trck_custom_2], 
 [trck_custom_3], 
 [trck_custom_4], 
 [trck_custom_5], 
 [trck_custom_6], 
 [trck_custom_7], 
 [trck_custom_8], 
 [trck_custom_9], 
 [AC_AcceptancyDate], 
 [AC_Status], 
 [AC_UnsubscribeDate], 
 [trck_is_consent], 
 [trck_is_participation], 
 [trck_participation_text], 
 [trck_is_subscribe], 
 [trck_subscribe_text], 
 [trck_is_usage], 
 [trck_usage_text], 
 [trck_campaign], 
 [trck_referer], 
 [trck_registration_ip], 
 [trck_subscribtion_ip], 
 [trck_subscribtion_source], 
 [trck_payload], 
 [Jobcode14], 
 [trck_source_system]
)
       SELECT s.[rnk], 
              s.[trck_ID], 
              s.[trck_touchpoint], 
              s.[trck_uniqueID], 
              s.[trck_market], 
              s.[trck_division], 
              s.[trck_brand], 
              s.[trck_segment], 
              s.[trck_email_address], 
              s.[trck_registration_date], 
              s.[trck_creation_date], 
              s.[trck_subscribtion_date], 
              s.[trck_doi], 
              s.[trck_is_unsubscribed], 
              s.[trck_unsubscribe_date], 
              s.[trck_is_contactable], 
              s.[trck_last_edited_date], 
              s.[trck_company_name], 
              s.[trck_title], 
              s.[trck_first_name], 
              s.[trck_last_name], 
              s.[trck_additional_name_information], 
              s.[trck_street], 
              s.[trck_house_number], 
              s.[trck_additional_address], 
              s.[trck_zip_code], 
              s.[trck_city], 
              s.[trck_state], 
              s.[trck_country], 
              s.[trck_gender], 
              s.[trck_birthday], 
              s.[trck_consent_text], 
              s.[trck_language], 
              s.[trck_mobile_number], 
              s.[trck_landline_number], 
              s.[trck_last_contact_date], 
              s.[trck_last_open_date], 
              s.[trck_last_click_date], 
              s.[trck_is_fake], 
              s.[trck_DMR], 
              s.[trck_DCR], 
              s.[trck_Source], 
              s.[trck_is_blocked], 
              s.[trck_blockreason], 
              s.[trck_change_comment], 
              s.[trck_custom_1], 
              s.[trck_custom_2], 
              s.[trck_custom_3], 
              s.[trck_custom_4], 
              s.[trck_custom_5], 
              s.[trck_custom_6], 
              s.[trck_custom_7], 
              s.[trck_custom_8], 
              s.[trck_custom_9], 
              s.[AC_AcceptancyDate], 
              s.[AC_Status], 
              s.[AC_UnsubscribeDate], 
              s.[trck_is_consent], 
              s.[trck_is_participation], 
              s.[trck_participation_text], 
              s.[trck_is_subscribe], 
              s.[trck_subscribe_text], 
              s.[trck_is_usage], 
              s.[trck_usage_text], 
              s.[trck_campaign], 
              s.[trck_referer], 
              s.[trck_registration_ip], 
              s.[trck_subscribtion_ip], 
              s.[trck_subscribtion_source], 
              s.[trck_payload], 
              s.[Jobcode14], 
              s.[trck_source_system]
       FROM [dbo].[tbl_TrackOne_MasterData_prepare] s
            LEFT OUTER JOIN dbo.[tbl_TrackOne_MasterData] t ON s.[trck_email_address] = t.[trck_email_address]
                                                               AND s.[trck_market] = t.[trck_market]
                                                               AND s.[trck_brand] = t.[trck_brand]
       WHERE NOT EXISTS
       (
           SELECT 1
           FROM dbo.[tbl_TrackOne_MasterData] m
           WHERE m.trck_email_address = s.trck_email_address
                 AND m.trck_brand = s.trck_brand
                 AND m.trck_market = s.trck_market
       );

-- delete from  dbo.[tbl_TrackOne_MasterData]

--
--instead merge update		   
UPDATE dbo.[tbl_TrackOne_MasterData]
  SET 
      RNK = S.RNK, 
      TRCK_ID = S.TRCK_ID, 
      TRCK_TOUCHPOINT = S.TRCK_TOUCHPOINT, 
      TRCK_UNIQUEID = S.TRCK_UNIQUEID, 
      TRCK_DIVISION = S.TRCK_DIVISION, 
      TRCK_SEGMENT = S.TRCK_SEGMENT, 
      TRCK_REGISTRATION_DATE = S.TRCK_REGISTRATION_DATE, 
      TRCK_CREATION_DATE = S.TRCK_CREATION_DATE, 
      TRCK_SUBSCRIBTION_DATE = S.TRCK_SUBSCRIBTION_DATE, 
      TRCK_DOI = S.TRCK_DOI, 
      TRCK_IS_UNSUBSCRIBED = S.TRCK_IS_UNSUBSCRIBED, 
      TRCK_UNSUBSCRIBE_DATE = S.TRCK_UNSUBSCRIBE_DATE, 
      TRCK_IS_CONTACTABLE = S.TRCK_IS_CONTACTABLE, 
      TRCK_LAST_EDITED_DATE = S.TRCK_LAST_EDITED_DATE, 
      TRCK_COMPANY_NAME = S.TRCK_COMPANY_NAME, 
      TRCK_TITLE = S.TRCK_TITLE, 
      TRCK_FIRST_NAME = S.TRCK_FIRST_NAME, 
      TRCK_LAST_NAME = S.TRCK_LAST_NAME, 
      TRCK_ADDITIONAL_NAME_INFORMATION = S.TRCK_ADDITIONAL_NAME_INFORMATION, 
      TRCK_STREET = S.TRCK_STREET, 
      TRCK_HOUSE_NUMBER = S.TRCK_HOUSE_NUMBER, 
      TRCK_ADDITIONAL_ADDRESS = S.TRCK_ADDITIONAL_ADDRESS, 
      TRCK_ZIP_CODE = S.TRCK_ZIP_CODE, 
      TRCK_CITY = S.TRCK_CITY, 
      TRCK_STATE = S.TRCK_STATE, 
      TRCK_COUNTRY = S.TRCK_COUNTRY, 
      TRCK_GENDER = S.TRCK_GENDER, 
      TRCK_BIRTHDAY = S.TRCK_BIRTHDAY, 
      TRCK_CONSENT_TEXT = S.TRCK_CONSENT_TEXT, 
      TRCK_LANGUAGE = S.TRCK_LANGUAGE, 
      TRCK_MOBILE_NUMBER = S.TRCK_MOBILE_NUMBER, 
      TRCK_LANDLINE_NUMBER = S.TRCK_LANDLINE_NUMBER, 
      TRCK_LAST_CONTACT_DATE = S.TRCK_LAST_CONTACT_DATE, 
      TRCK_LAST_OPEN_DATE = S.TRCK_LAST_OPEN_DATE, 
      TRCK_LAST_CLICK_DATE = S.TRCK_LAST_CLICK_DATE, 
      TRCK_IS_FAKE = S.TRCK_IS_FAKE, 
      TRCK_DMR = S.TRCK_DMR, 
      TRCK_DCR = S.TRCK_DCR, 
      TRCK_SOURCE = S.TRCK_SOURCE, 
      TRCK_IS_BLOCKED = S.TRCK_IS_BLOCKED, 
      TRCK_BLOCKREASON = S.TRCK_BLOCKREASON, 
      TRCK_CHANGE_COMMENT = S.TRCK_CHANGE_COMMENT, 
      TRCK_CUSTOM_1 = S.TRCK_CUSTOM_1, 
      TRCK_CUSTOM_2 = S.TRCK_CUSTOM_2, 
      TRCK_CUSTOM_3 = S.TRCK_CUSTOM_3, 
      TRCK_CUSTOM_4 = S.TRCK_CUSTOM_4, 
      TRCK_CUSTOM_5 = S.TRCK_CUSTOM_5, 
      TRCK_CUSTOM_6 = S.TRCK_CUSTOM_6, 
      TRCK_CUSTOM_7 = S.TRCK_CUSTOM_7, 
      TRCK_CUSTOM_8 = S.TRCK_CUSTOM_8, 
      TRCK_CUSTOM_9 = S.TRCK_CUSTOM_9, 
      AC_ACCEPTANCYDATE = S.AC_ACCEPTANCYDATE, 
      AC_STATUS = S.AC_STATUS, 
      AC_UNSUBSCRIBEDATE = S.AC_UNSUBSCRIBEDATE, 
      TRCK_IS_CONSENT = S.TRCK_IS_CONSENT, 
      TRCK_IS_PARTICIPATION = S.TRCK_IS_PARTICIPATION, 
      TRCK_PARTICIPATION_TEXT = S.TRCK_PARTICIPATION_TEXT, 
      TRCK_IS_SUBSCRIBE = S.TRCK_IS_SUBSCRIBE, 
      TRCK_SUBSCRIBE_TEXT = S.TRCK_SUBSCRIBE_TEXT, 
      TRCK_IS_USAGE = S.TRCK_IS_USAGE, 
      TRCK_USAGE_TEXT = S.TRCK_USAGE_TEXT, 
      TRCK_CAMPAIGN = S.TRCK_CAMPAIGN, 
      TRCK_REFERER = S.TRCK_REFERER, 
      TRCK_REGISTRATION_IP = S.TRCK_REGISTRATION_IP, 
      TRCK_SUBSCRIBTION_IP = S.TRCK_SUBSCRIBTION_IP, 
      TRCK_SUBSCRIBTION_SOURCE = S.TRCK_SUBSCRIBTION_SOURCE, 
      TRCK_PAYLOAD = S.TRCK_PAYLOAD, 
      JOBCODE14 = S.JOBCODE14, 
      TRCK_SOURCE_SYSTEM = S.TRCK_SOURCE_SYSTEM
FROM
(
    SELECT ist.[rnk], 
           ist.[trck_ID], 
           ist.[trck_touchpoint], 
           ist.[trck_uniqueID], 
           ist.[trck_market], 
           ist.[trck_division], 
           ist.[trck_brand], 
           ist.[trck_segment], 
           ist.[trck_email_address], 
           ist.[trck_registration_date], 
           ist.[trck_creation_date], 
           ist.[trck_subscribtion_date], 
           ist.[trck_doi], 
           ist.[trck_is_unsubscribed], 
           ist.[trck_unsubscribe_date], 
           ist.[trck_is_contactable], 
           ist.[trck_last_edited_date], 
           ist.[trck_company_name], 
           ist.[trck_title], 
           ist.[trck_first_name], 
           ist.[trck_last_name], 
           ist.[trck_additional_name_information], 
           ist.[trck_street], 
           ist.[trck_house_number], 
           ist.[trck_additional_address], 
           ist.[trck_zip_code], 
           ist.[trck_city], 
           ist.[trck_state], 
           ist.[trck_country], 
           ist.[trck_gender], 
           ist.[trck_birthday], 
           ist.[trck_consent_text], 
           ist.[trck_language], 
           ist.[trck_mobile_number], 
           ist.[trck_landline_number], 
           ist.[trck_last_contact_date], 
           ist.[trck_last_open_date], 
           ist.[trck_last_click_date], 
           ist.[trck_is_fake], 
           ist.[trck_DMR], 
           ist.[trck_DCR], 
           ist.[trck_Source], 
           ist.[trck_is_blocked], 
           ist.[trck_blockreason], 
           ist.[trck_change_comment], 
           ist.[trck_custom_1], 
           ist.[trck_custom_2], 
           ist.[trck_custom_3], 
           ist.[trck_custom_4], 
           ist.[trck_custom_5], 
           ist.[trck_custom_6], 
           ist.[trck_custom_7], 
           ist.[trck_custom_8], 
           ist.[trck_custom_9], 
           ist.[AC_AcceptancyDate], 
           ist.[AC_Status], 
           ist.[AC_UnsubscribeDate], 
           ist.[trck_is_consent], 
           ist.[trck_is_participation], 
           ist.[trck_participation_text], 
           ist.[trck_is_subscribe], 
           ist.[trck_subscribe_text], 
           ist.[trck_is_usage], 
           ist.[trck_usage_text], 
           ist.[trck_campaign], 
           ist.[trck_referer], 
           ist.[trck_registration_ip], 
           ist.[trck_subscribtion_ip], 
           ist.[trck_subscribtion_source], 
           ist.[trck_payload], 
           ist.[Jobcode14], 
           ist.[trck_source_system]
    FROM [dbo].[tbl_TrackOne_MasterData_prepare] AS ist
    WHERE ist.[trck_email_address] = [trck_email_address]
          AND ist.[trck_market] = [trck_market]
          AND ist.[trck_brand] = [trck_brand]
    EXCEPT
    SELECT ita.[rnk], 
           ita.[trck_ID], 
           ita.[trck_touchpoint], 
           ita.[trck_uniqueID], 
           ita.[trck_market], 
           ita.[trck_division], 
           ita.[trck_brand], 
           ita.[trck_segment], 
           ita.[trck_email_address], 
           ita.[trck_registration_date], 
           ita.[trck_creation_date], 
           ita.[trck_subscribtion_date], 
           ita.[trck_doi], 
           ita.[trck_is_unsubscribed], 
           ita.[trck_unsubscribe_date], 
           ita.[trck_is_contactable], 
           ita.[trck_last_edited_date], 
           ita.[trck_company_name], 
           ita.[trck_title], 
           ita.[trck_first_name], 
           ita.[trck_last_name], 
           ita.[trck_additional_name_information], 
           ita.[trck_street], 
           ita.[trck_house_number], 
           ita.[trck_additional_address], 
           ita.[trck_zip_code], 
           ita.[trck_city], 
           ita.[trck_state], 
           ita.[trck_country], 
           ita.[trck_gender], 
           ita.[trck_birthday], 
           ita.[trck_consent_text], 
           ita.[trck_language], 
           ita.[trck_mobile_number], 
           ita.[trck_landline_number], 
           ita.[trck_last_contact_date], 
           ita.[trck_last_open_date], 
           ita.[trck_last_click_date], 
           ita.[trck_is_fake], 
           ita.[trck_DMR], 
           ita.[trck_DCR], 
           ita.[trck_Source], 
           ita.[trck_is_blocked], 
           ita.[trck_blockreason], 
           ita.[trck_change_comment], 
           ita.[trck_custom_1], 
           ita.[trck_custom_2], 
           ita.[trck_custom_3], 
           ita.[trck_custom_4], 
           ita.[trck_custom_5], 
           ita.[trck_custom_6], 
           ita.[trck_custom_7], 
           ita.[trck_custom_8], 
           ita.[trck_custom_9], 
           ita.[AC_AcceptancyDate], 
           ita.[AC_Status], 
           ita.[AC_UnsubscribeDate], 
           ita.[trck_is_consent], 
           ita.[trck_is_participation], 
           ita.[trck_participation_text], 
           ita.[trck_is_subscribe], 
           ita.[trck_subscribe_text], 
           ita.[trck_is_usage], 
           ita.[trck_usage_text], 
           ita.[trck_campaign], 
           ita.[trck_referer], 
           ita.[trck_registration_ip], 
           ita.[trck_subscribtion_ip], 
           ita.[trck_subscribtion_source], 
           ita.[trck_payload], 
           ita.[Jobcode14], 
           ita.[trck_source_system]
    FROM [dbo].[tbl_TrackOne_MasterData] AS ita
    WHERE ita.[trck_email_address] = [trck_email_address]
          AND ita.[trck_market] = [trck_market]
          AND ita.[trck_brand] = [trck_brand]
) AS S
WHERE [tbl_TrackOne_MasterData].[trck_email_address] = S.[trck_email_address]
      AND [tbl_TrackOne_MasterData].[trck_market] = S.[trck_market]
      AND [tbl_TrackOne_MasterData].[trck_brand] = S.[trck_brand];